### PR TITLE
Completion

### PR DESCRIPTION
**Pull request by nbehrnd**
The project is mirrored on PyPi which eases installation of the code (including dependencies) and eventual use.  Thus the relevant information was added/adjusted in the documentation.

### CODE REVIEW

**Comment by novoid** [comment]
Thanks for your fixes! Good idea!

**Comment by novoid** [comment]
By the way: do people use pypi to browse for tools? I only was using pypi via "pip search foo" and "pip install foo" only ...

**Comment by nbehrnd** [comment]
Re search on pypi:  There are occasions where I do because one may search by name _known/guessed_ .or. by topics which  are organized in a `tree`-like pattern.  It is handy to combine e.g. tag `chemistry` (approx. 0.9k entries) with `database` to narrow the list to 14 entries only including [pubchempy](https://pypi.org/project/PubChemPy/).  (It is an interface to one of the public databases by the U.S. NIH, [pubchem](https://pubchem.ncbi.nlm.nih.gov/).  This offers access to a selection of the record fields of indexed compounds; one likely could compute some/many of them locally, yet fetching the [already curated] results often is faster.):

PyPi_pattern

Somehow the suggestion to add the link to the PyPi repository (different name) to the `README.org` didn't pass.  While a merge _as such_  or in a modified version remains yours, is it a better fit for your workflow if I would file the merge requests on an atomic basis, i.e. one for adding the link to PyPi, and an other about the alias?  (Conceptually perceived as related with each other, the two were filed simultaneously.)

**Comment by novoid** [comment]
I'd prefer separate ones, yes. In this case, they were pretty much related and I didn't care. 

Thanks for the insight!

**Pull request closed without merging**
